### ISSUE TITLE
Training on single node

### ISSUE THREAD

**Issue by mtmyyy** [yuzhms/Streaming-Video-Model#3]
Hi, when i execute `bash ./tools/dist_train.sh configs/mot/svm/svm_base.py 8 --cfg-options model.detector.backbone.pretrain=./pretrain/ViT-B-16.pt`, the following error occurs, and i didnot make any changes to the file you provided.
```
./tools/dist_train.sh: 行 2: $'\r'：未找到命令
./tools/dist_train.sh: 行 9: $'\r'：未找到命令
./tools/dist_train.sh: 行 10: $'\r'：未找到命令
/cver/tcying/lib/python3.8/site-packages/torch/distributed/launch.py:178: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torch.distributed.run.
Note that --use_env is set by default in torch.distributed.run.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
': [Errno 2] No such file or directoryle '
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 2) local_rank: 0 (pid: 4109832) of binary: /cver/tcying/bin/python
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/cver/tcying/lib/python3.8/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/cver/tcying/lib/python3.8/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/cver/tcying/lib/python3.8/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/cver/tcying/lib/python3.8/site-packages/torch/distributed/run.py", line 689, in run
    elastic_launch(
  File "/cver/tcying/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 116, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/cver/tcying/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 244, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
***************************************
 FAILED               
=======================================
Root Cause:
[0]:
  time: 2023-06-14_19:05:08
  rank: 0 (local_rank: 0)
  exitcode: 2 (pid: 4109832)
  error_file: <N/A>
  msg: "Process failed with exitcode 2"
=======================================
Other Failures:
  <NO_OTHER_FAILURES>
***************************************

./tools/dist_train.sh: 行 12: $'--nnodes=1\r'：未找到命令
./tools/dist_train.sh: 行 13: $'--node_rank=0\r'：未找到命令
./tools/dist_train.sh: 行 14: $'--master_addr=127.0.0.1\r'：未找到命令
./tools/dist_train.sh: 行 15: $'--nproc_per_node=1\r'：未找到命令
./tools/dist_train.sh: 行 16: $'--master_port=29500\r'：未找到命令
./tools/dist_train.sh: 行 17: ./tools/train.py: 权限不够
: 没有那个文件或目录h: 行 18: configs/mot/svm/svm_base.py
./tools/dist_train.sh: 行 19: --launcher：未找到命令
./tools/dist_train.sh: 行 20: --work-dir：未找到命令
./tools/dist_train.sh: 行 21: --cfg-options：未找到命令
```

**Comment by yuzhms** [comment]
It should be related to the wrong line endings. See https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings?platform=linux

**Comment by mtmyyy** [comment]
I have solved the problem. 
In your `dist_train.sh` file, the spaces in the second and ninth lines caused this problem. When I removed the spaces, I resolved it.
